Pets/urls.py
from django.contrib import admin
from django.urls import path, include
from app.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/urls.py
from django.urls import path
from .views import IndexView, HomeView, RegisterView, logout_view

urlpatterns = [
    path('', HomeView.as_view({'get': 'home', 'post': 'home'}), name='home'),
    path('index/', IndexView.as_view({'get': 'list'}), name='index'),
    path('register/', RegisterView.as_view({'get': 'register', 'post': 'register'}), name='register'),
    path('logout/', logout_view, name='logout'),
]

app/models.py
from django.db import models

# Create your models here.

class Users(models.Model):
    name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    age = models.IntegerField()
    phone_number = models.IntegerField()
    email = models.EmailField()
    
    def __str__(self):
        texto = '{0} {1} {2} {3} {4}'
        return texto.format(self.name,self.last_name,self.age,self.phone_number,self.email)
    
    class Meta:
        db_table = 'User'
        
class Pets(models.Model):
    name = models.CharField(max_length=150)
    race = models.CharField(max_length=150)
    age = models.IntegerField()
    
    def __str__(self):
        texto = '{0} {1} {2}'
        return texto.format(self.name,self.race,self.age)
    
    class Meta:
        db_table = 'Pet'

app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from rest_framework import viewsets
from rest_framework.permissions import AllowAny
from rest_framework import authentication
from .serializers import UsersSerializer
from .models import Users

class HomeView(viewsets.ViewSet):
    
    def home(self, request):
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index')
            else:
                return render(request, 'home.html', {'error': 'Invalid credentials'})
        return render(request, 'home.html')
    
def logout_view(request):
    logout(request)
    return redirect('home')

class RegisterView(viewsets.ViewSet):
    
    def register(self, request):
        if request.method == 'POST':
            serializer = UsersSerializer(data=request.POST)
            if serializer.is_valid():
                serializer.save()
                
                username = request.POST.get('username')
                password = request.POST.get('password')
                
                # Crear un usuario en el sistema de autenticación de Django
                user = User.objects.create_user(username=username, password=password)
                
                # Autenticar y loguear al usuario
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    return redirect('index')
                else:
                    return render(request, 'register.html', {'serializer': serializer, 'error': 'Authentication failed'})
            else:
                print(serializer.errors) 
                return render(request, 'register.html', {'serializer': serializer, 'error': 'Invalid data'})
        else:
            serializer = UsersSerializer()
            
        return render(request, 'register.html', {'serializer': serializer})

class IndexView(viewsets.ViewSet):
    permission_classes = [AllowAny]
    authentication_classes = [authentication.SessionAuthentication]

    def list(self, request):
        queryset = Users.objects.all()
        serializer = UsersSerializer(queryset, many=True)
        context = {
            'users': serializer.data
        }
        return render(request, 'index.html', context)

templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Pets Friendly</title>
</head>
<body>
    {% include 'navBar.html' %}

    <h2>Welcome Family and Pets</h2>

    {% block content %}
    <form action="{% url 'home' %}" method="post">
        {% csrf_token %}
        <label for="id_username">Username:</label>
        <input type="text" id="id_username" name="username" placeholder="Enter your username" required>
        <br>
        <label for="id_password">Password:</label>
        <input type="password" id="id_password" name="password" placeholder="Enter your password" required>
        <br>
        <input type="submit" value="Login">
    </form>

    {% if error %}
    <p style="color: red;">{{ error }}</p>
    {% endif %}

    <p><a href="{% url 'register' %}">Register</a></p>
    {% endblock %}

    <!--bootstrap Javascritp-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
    <h1>Lista de Usuarios</h1>
    <ul>
        {% for user in users %}
        <li>{{ user.name }} {{ user.last_name }} ({{ user.email }})</li>
        {% endfor %}
    </ul>
    
    <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Logout">
    </form>

    <p><a href="{% url 'home' %}">Back to Home</a></p>
</body>
</html>

templates/navBar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
<div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
        </a>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
        </ul>
        </li>
        <li class="nav-item">
        <a class="nav-link disabled" aria-disabled="true">Disabled</a>
        </li>
    </ul>
    <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
    </div>
</div>
</nav>

templates/register.html
{% extends "home.html" %}

{% block content %}
    <h3>Registro de Usuario</h3>
    
    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        {{ serializer.as_p }}

        <label for="id_name">Name:</label>
        <input type="text" id="id_name" name="name" placeholder="Insert your name" required>
        <br>
        <label for="id_lastName">Last Name:</label>
        <input type="text" id="id_lastName" name="last_name" placeholder="Insert your last name" required>
        <br>
        <label for="id_age">Age:</label>
        <input type="number" id="id_age" name="age" placeholder="Insert your age" required>
        <br>
        <label for="id_phone_number">Phone Number:</label>
        <input type="text" id="id_phone_number" name="phone_number" placeholder="Insert your number" required>
        <br>
        <label for="id_email">Email:</label>
        <input type="email" id="id_email" name="email" placeholder="Insert your email" required>
        <br>
        <label for="id_username">Username:</label>
        <input type="text" id="id_username" name="username" placeholder="Enter your username" required>
        <br>
        <label for="id_password">Password:</label>
        <input type="password" id="id_password" name="password" placeholder="Enter your password" required>
        <br>
        <input type="submit" value="Register">
    </form>
    
    {% if error %}
    <p style="color: red;">{{ error }}</p>
    {% endif %}
    
    <p><a href="{% url 'home' %}">Back to Home</a></p>
{% endblock %}